### ISSUE TITLE
关于网易云音乐的首页banner轮播

### ISSUE THREAD

**Issue by zaaach** [wuyr/LitePager#6]
我一直想用recyclerview实现轮播广告，作为列表的头部使用，但由于比较菜，实际上遇到有很多问题不知道如何解决，只能希望大佬能抽时间实现一下如果可以的话

**Comment by wuyr** [comment]
已Mark，感谢提出~

**Comment by wuyr** [comment]
同学你好，1.3.0版本已添加【设置自动轮播】功能。

**Comment by zaaach** [comment]
感谢大佬！
